FROM maven:3.9.6-eclipse-temurin-17-alpine
WORKDIR /app
COPY . .
WORKDIR /app/springboot_paractice/demo
RUN mvn clean package -DskipTests
EXPOSE 8080
CMD ["java", "-jar", "target/demo-0.0.1-SNAPSHOT.jar"]
