spring.application.name=spring_boot_paractice

spring.datasource.url=jdbc:mysql://localhost:3306/tanvir_database
spring.datasource.username=root
spring.datasource.password=Tanvir@9110
spring.jpa.hibernate.ddl-auto=update

